name: habit_tracker
description: "A new Flutter project."

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  catppuccin_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^4.0.0
  get: ^4.7.1
  # supabase_flutter: ^1.10.14
  flutter_secure_storage: ^10.0.0-beta.4
  # uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.1
  supabase_flutter: ^2.8.4
dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  # uses-asset-bundle-paths: true
  assets:
    - assets/image/

  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
icons_launcher:
  image_path: "assets/image/icon/icon for habit_tracker app.png"
  platforms:
    ios:
      enable: true
    android:
      enable: true
    linux:
      enable: true
      image_path: "assets/image/icon/icon for habit_tracker app.png"
