import 'dart:convert';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:image_picker/image_picker.dart';

// ── CUSTOM GEMINI EXCEPTIONS ──────────────────────────────────────────────────
abstract class GeminiException implements Exception {
  final String message;
  final String? details;

  GeminiException(this.message, {this.details});

  @override
  String toString() => message;
}

class ApiKeyMissingException extends GeminiException {
  ApiKeyMissingException()
      : super('GEMINI_API_KEY is not defined in your environment (.env file).');
}

class GeminiInvalidResponseException extends GeminiException {
  GeminiInvalidResponseException(String message, {String? details})
      : super(message, details: details);
}

class GeminiQuotaException extends GeminiException {
  GeminiQuotaException(String message, {String? details})
      : super(message, details: details);
}

class GeminiServerException extends GeminiException {
  GeminiServerException(String message, {String? details})
      : super(message, details: details);
}

class GeminiUnknownException extends GeminiException {
  GeminiUnknownException(String message, {Object? originalError})
      : super(message, details: originalError?.toString());
}

// ── GEMINI SERVICE ────────────────────────────────────────────────────────────
class GeminiService {
  GenerativeModel? _modelInstance;

  /// Lazy getter for standard GenerativeModel instance
  GenerativeModel get _model {
    if (_modelInstance != null) return _modelInstance!;

    final apiKey = dotenv.env['GEMINI_API_KEY'];
    if (apiKey == null || apiKey.isEmpty) {
      throw ApiKeyMissingException();
    }

    _modelInstance = GenerativeModel(
      model: 'gemini-2.5-flash-lite',
      apiKey: apiKey,
      generationConfig: GenerationConfig(
        responseMimeType: 'application/json',
      ),
    );
    return _modelInstance!;
  }

  /// Evaluates an image using Gemini Pro Vision and extracts distinct habits/tasks.
  Future<List<String>> extractHabitsFromImage(XFile imageFile) async {
    try {
      final bytes = await imageFile.readAsBytes();
      final prompt = TextPart(
        'You are an expert habit coach and productivity analyst.\n'
        'Role: You are a professional daily habit and task extractor.\n'
        'Task: Analyze the provided image (handwritten list, schedule, or diet plan) and extract all habits/tasks.\n'
        'Strict Formatting Rules:\n'
        '1. Output ONLY a valid JSON array of strings: ["Category: Emoji Task", "Category: Emoji Task"].\n'
        '2. NO markdown blocks (e.g., no ```json), NO introductory text.\n'
        '3. For grouped items (like under "Breakfast" or "Lunch"), prefix each task with the group name followed by a colon.\n'
        '4. Add a relevant emoji at the beginning of the task text (after the colon if there is a category).\n'
        '   Example: ["Breakfast: 🍳 3 eggs", "Lunch: 🍗 Chicken thighs", "Dinner: 🥩 Beef", "💊 Creatine"]\n'
        '5. Keep each string very short (2-5 words) and actionable.\n'
        '6. If an item is alone without a category, just list its name with an emoji.\n'
        '7. Maintain the original language of the image (Arabic or English).\n'
        '8. Avoid duplicates: If multiple words mean the same thing, output only one.',
      );
      
      final imagePart = DataPart(imageFile.mimeType ?? 'image/jpeg', bytes);

      final response = await _model.generateContent([
        Content.multi([prompt, imagePart]),
      ]);

      if (response.text == null || response.text!.isEmpty) {
        throw GeminiInvalidResponseException('No response was generated by the AI.');
      }

      String cleanedText = response.text!.trim();
      // Enforce clean JSON boundary if markdown wraps it
      if (cleanedText.startsWith('```json')) {
        cleanedText = cleanedText.replaceFirst('```json\n', '');
      } else if (cleanedText.startsWith('```')) {
        cleanedText = cleanedText.replaceFirst('```\n', '');
      }
      if (cleanedText.endsWith('```')) {
        cleanedText = cleanedText.substring(0, cleanedText.length - 3).trim();
      }

      final decoded = jsonDecode(cleanedText);
      if (decoded is! List) {
        throw GeminiInvalidResponseException('Expected a JSON list of habits/tasks.');
      }

      return decoded.map((e) => e.toString()).toList();
    } catch (e) {
      _handleException(e, 'extracting habits from image');
    }
  }

  /// Starts a new chat session with an optional system instruction.
  ChatSession startChat({String? systemInstruction}) {
    try {
      final apiKey = dotenv.env['GEMINI_API_KEY'];
      if (apiKey == null || apiKey.isEmpty) {
        throw ApiKeyMissingException();
      }

      final chatModel = GenerativeModel(
        model: 'gemini-3.5-flash',
        apiKey: apiKey,
        systemInstruction: systemInstruction != null ? Content.system(systemInstruction) : null,
      );

      return chatModel.startChat();
    } catch (e) {
      _handleException(e, 'starting chat session');
    }
  }

  /// Centralized exception analyzer mapping errors to custom GeminiExceptions.
  Never _handleException(Object e, String action) {
    if (e is GeminiException) {
      throw e;
    }

    if (e is FormatException) {
      throw GeminiInvalidResponseException(
        'Failed to parse the AI response format during $action.',
        details: e.toString(),
      );
    }

    if (e is GenerativeAIException) {
      final errorMsg = e.message.toLowerCase();
      if (errorMsg.contains('quota') || errorMsg.contains('limit') || errorMsg.contains('429')) {
        throw GeminiQuotaException(
          'API rate limit exceeded. Please try again later.',
          details: e.message,
        );
      } else if (errorMsg.contains('api key') || errorMsg.contains('invalid') || errorMsg.contains('400')) {
        throw GeminiServerException(
          'Invalid or missing API key configuration.',
          details: e.message,
        );
      } else {
        throw GeminiServerException(
          'Gemini server returned an error during $action.',
          details: e.message,
        );
      }
    }

    throw GeminiUnknownException(
      'An unexpected error occurred while $action.',
      originalError: e,
    );
  }
}
