import 'dart:convert';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:image_picker/image_picker.dart';
import 'package:flutter/foundation.dart';

class GeminiService {
  late final GenerativeModel _model;

  GeminiService() {
    final apiKey = dotenv.env['GEMINI_API_KEY'];
    if (apiKey == null || apiKey.isEmpty) {
      throw Exception('GEMINI_API_KEY not found in .env file');
    }

    _model = GenerativeModel(
      model: 'gemini-2.5-flash',
      apiKey: apiKey,
    );
    
  }



  /// Evaluates an image using Gemini Pro Vision and extracts distinct habits/tasks.
  Future<List<String>> extractHabitsFromImage(XFile imageFile) async {
    try {
      final bytes = await imageFile.readAsBytes();
      final prompt = TextPart(
        'Extract a list of habits or tasks from this image. '
        'Return only a simple JSON array of strings. '
        'Example: ["Task 1", "Task 2"]',
      );
      final imagePart = DataPart(imageFile.mimeType ?? 'image/jpeg', bytes);

      final response = await _model.generateContent([
        Content.multi([prompt, imagePart])
      ]);

      if (response.text == null || response.text!.isEmpty) {
        throw Exception('No response generated by the AI.');
      }

      String cleanedText = response.text!.trim();
      // Sometimes models enforce markdown code blocks despite prompts. Handle defensively:
      if (cleanedText.startsWith('```json')) {
        cleanedText = cleanedText.replaceFirst('```json\n', '');
      } else if (cleanedText.startsWith('```')) {
        cleanedText = cleanedText.replaceFirst('```\n', '');
      }
      if (cleanedText.endsWith('```')) {
        cleanedText = cleanedText.substring(0, cleanedText.length - 3).trim();
      }

      final List<dynamic> decoded = jsonDecode(cleanedText);
      final List<String> parsedHabits = decoded.map((e) => e.toString()).toList();

      return parsedHabits;
    } catch (e) {
      debugPrint('Error extracting habits from image: $e');
      throw Exception('Failed to extract habits: $e');
    }
  }
}
